name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.build-step.outputs.build-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm install

      - name: Clear project
        run: npm run clear

      - name: Build project
        id: build-step
        run: |
          npm run build
          echo "build-path=build/" >> $GITHUB_OUTPUT

  deploy-jdcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to JDCloud
        uses: easingthemes/ssh-deploy@v4.1.10
        with:
          SSH_PRIVATE_KEY: ${{ secrets.JD_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.JD_USER_HOST }}
          REMOTE_USER: ${{ secrets.JD_USER_NAME }}
          SOURCE: "${{ needs.build.outputs.build-path }}"
          ARGS: "-rltgoDzvO --delete"
          TARGET: /data/docker/nginx/html/build
